site_name: Mixed Traffic Control

nav:
    - Welcome: index.md
    - Smoothing traffic flow: smoothing_traffic_flow.md
    - Structured optimal control: structured_optimal_control.md
    - Cooperative formation multiple: cooperative_formation_multiple.md
theme: readthedocs
